# MongoID Database Config
# This file has been hacked to read all settings from the
# database_config sub-hash in config/application.yml.
#
# Unless you are absolutely sure of yourself, you should not
# edit this file.

<% require File.expand_path( '../config/environment', __FILE__ ) %>

common: &common
  <% Settings.database_config.each do |key, val| %>
    <% if key and val %>
      <%= "#{key.to_s}: #{val.to_s}" %>
    <% end %>
  <% end %>

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common

heroku:
  <<: *common

